language: java
branches:
  only:
    - master

# MySql 5.6
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE oncontrolhome;'
  - mysqladmin -u root password root
  - sudo service mysql restart

### HEROKU DEPLOYMENT
#deploy:
#  provider: heroku
#  api_key:
#    secure: SOjKDt7xeB8+XCCE40RC2CoV1fdkp3Vmpj+Mg01YH8+NxnTrK9Y/FpwG3rF2oC8yuCSHT7IIpbZ7uk0E4tzC39LTDBMQsY1ArACjb6DLV3e4+ey34RvyWxiHlUGSL1ysE/baTizHVSiaY2K7+t9EFGCgtGRPlEY6wFnCvDm1BVGUPZYmU5qp06KGoaJY6Sk0dkVgmMAW/jOHIc8cqHDZerqaT3tmGmZuM/sY9vQbz0HNMBqgynGh6eqIwfmEvqkfIRUi14gK8mncHoM3i9y1g5M2CP/M+ShsxvsbLQTVFZhFWirtnOk41JzCPNrjkDEI/y1YTOSMT6SkzHifXlccg7sUKBLoccnGd3U5prVvGifCJayXqWfry+GMIeiWA/cfTO/rBDfP5+lr0/TlcUqD/yYyywPBApH6i5mkif7ezkya+7YId4A8Wh08W+91XbPgAVLmLm8iVHGJYkV9todm+e/+wmXhB179gLs+IpHS2wAKFt0m/d2UdtwLct+8xlXnC7avypmnMkDsaUaRBA3ZnbQEG2p6LJAdA4Y1Hynv/p6cZARtaxjW/AU9QqTkPkuyB/Ndz0luaNf7wxu0J38zY9iFLhzpFUpXPJADT7m7JBI2C9m4EgkBSG5Y97SnMEyG5ko2yx1nOkDYcZ11VlJ1T6Tc5ZuIcumz7ZQ5xNdgCjI=
#  app: on-control-home
#  on:
#    repo: Hgmoa/DesarrolloAplicacionesWeb


### SonarCloud Metrics
addons:
  sonarcloud:
    organization: "oncontrolhome"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
    # Github token so sonar can comment on pull request
    github_token:
          secure: Fcx4NvPGHerOyAM3rqB2gfkxl49qts1otY4R2FCqymGt0kPrEw+rwU5i8Ew50kLSUCs833BxDAZRO+XWvNOycEiwaOGZ3cXHYIcMoDfQj4wq8IBCzeykd2he/LaJh8oi59heDJMSHzIHxzYNap6vnfjNWV5BYq0jeK00xCnhxGogkhtpuVSrU3RwvBZs8B31VUaGlFfHhLYcXODpdih85P0Mi68tS4C6gUv1V7WOXWH7dlISiavN6wtkMDNRgWz80rg7Gc2YOQoEgvJRiqXtGQjvL6XP0mjqFkvHPRCjPsCA/vELaRrAAjbjdF+vRnhqq2yr5Sg17LEXO20dukwsAoplXrk1VDxVxNlWAUdXdi36MpkTE/5nazrwwCizaot6nqioc5d1eybc9o2ykaYj9dmJxj5XJMLX945viE4Qm6xmtxZytPgi4/7/kuw3vCcpZe75EqnemJN01J0H7JAXTbegGnFby/tTM8lUc0GN65GtWKf2K7EmBQ2FOeTOQqFNyQkmdfZHc+Cg4ClFj/2tzkaohzc6pMYEg0mDRk0Jitdf7L5+v6hcVO3AS/bJLXNxn/wwfle8VBTpxFC14EO0VGh6XsudMmP7Hjtq3C2uRq9J9yZmh5zcITmlnlMsGX9BQUFz0l5HjCU2vGsZjtlcYwMZNTkNYLXzoU/gwj23Oc4=


script:
  # Builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


# Cache to speed up travis a bit
cache:
  directories:
  - .autoconf
  - $HOME/.m2